### ISSUE TITLE
Doesn't work with last version on React native (0.63.3)

### ISSUE THREAD

**Issue by Navipro70** [kashishgrover/react-native-see-more-inline#13]
[IOS] After installation and updating pods show this error:

`RCTF Fatal
Error: Unable to resolve module react-native-text-size from node_modules/react-native-see-more-inline/src/SeeMore/SeeMoreUtil.js: react-native-text-size could not be found within the project.
`

Version on React Native is [0.63.3]

**Comment by kashishgrover** [comment]
Hi @Navipro70 . Can you check whether `react-native-text-size` is installed in your project? From the error code it looks like you may have missed that. Just refer the readme once again,

**Comment by Navipro70** [comment]
Hello @kashishgrover 
Oh sorry, I missed)
But why this library in require for `react-native-see-more-inline`?

**Comment by kashishgrover** [comment]
@Navipro70 It is needed to calculate the width of the text based on font and the size used. That is what allows us to sort of try and figure out where to place the "see more" text in the paragraph. 

Please close this issue if you were able to figure out the problem.
