### ISSUE TITLE
Error in install

### ISSUE THREAD

**Issue by dev-jccastro** [kashishgrover/react-native-see-more-inline#8]
It seems the library is not registered on NPM? I keep on getting 

npm ERR! 404  'native-see-more-inline@1.2.0' is not in the npm registry.

Can you have a look on this? Thanks

**Comment by kashishgrover** [comment]
Not sure why you are getting this error. Would be great if you can share the exact command you ran and the exact error message you got. You can share a snippet/screenshot from your terminal.

**Comment by dev-jccastro** [comment]
Hi @kashishgrover not sure what happened last time I tried to install the package, but it's properly working right now. I'll close this, thanks!
